### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by lpil** [knrz/proplist#2]
This module would be much nicer with some inline docs :)

**Comment by CyrusNuevoDia** [comment]
It would!

Until I get around to doing it (soon—I promise!), the docs for `Keyword.function/n` apply to `Proplist.function/n` :shipit:.

Actually you can always use the docs for `Keyword.function/n`, since the functions are the same :+1:

**Comment by CyrusNuevoDia** [comment]
Docs are up! :shipit:
